name: AKS Multi-Env Deployment with WhatIf (Terraform)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select environment
        required: true
        type: choice
        options:
          - dev
          - test
          - prod

env:
  TF_WORKING_DIR: 

jobs:
  # =========================
  # ENV - WHATIF
  # =========================
  plan:
    name: Terraform Plan (What-If)
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Validate
        run: terraform validate
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Plan
        run: terraform plan -var-file="${ENV}.tfvars" -out=tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Upload Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan-${{ env.ENV }}
          path: ${{ env.TF_WORKING_DIR }}/tfplan

# =========================
# ENV - DEPLOY
# =========================
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan
    environment: ${{ github.event.inputs.environment }}

    env:
      ENV: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ${{ env.TF_WORKING_DIR }}

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan-${{ env.ENV }}
          path: ${{ env.TF_WORKING_DIR }}

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: ${{ env.TF_WORKING_DIR }}
